Fix registry nginx proxy_pass url
This change fixes a problem in the nginx proxy pass rule that handles
requests to the container registry in API v2, observed when using
Podman to push container images.

The configuration file had the following rule:

    location /v2/ {
        ...
        proxy_pass https://127.0.0.1:5000/;

Notice the trailing slash. This effectively strips the /v2/ prefix and
causes problems when pushing images:

    Error: writing blob: initiating layer upload to /v2/telcov10n-ci/set-inventory/blobs/uploads/
    in bastion.kni-qe-106.telco5gran.eng.rdu2.redhat.com: StatusCode: 404, "404 page not found\n"

Removing the trailing slash fixes the problem.